
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: stock_app
  password: <%= ENV['STOCK_APP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: stock_app_development

test:
  <<: *default
  database: stock_app_test

production:
  <<: *default
  database: stock_app_production
  
